Repository photosynthesis-team/piq, pull requests merged in 2020-06, with the labels that each got.

#78 Update TV interface
  photosynthesis_metrics/gmsd.py
  photosynthesis_metrics/ssim.py
  photosynthesis_metrics/tv.py
  photosynthesis_metrics/utils.py
  photosynthesis_metrics/vif.py
  tests/test_tv.py
  tests/test_utils.py
Labels: refactoring

#85 Add __version__ attribute
  photosynthesis_metrics/__init__.py
  setup.py
Labels: feature

#103 Bugfix for FID
  photosynthesis_metrics/fid.py
Labels: bug

#88 Bug fix for BRISQUE score
  photosynthesis_metrics/brisque.py
  photosynthesis_metrics/utils.py
  tests/test_brisque.py
Labels: bug

#96 feature/issue#26: Perceptual losses
  piq/__init__.py
  piq/perceptual.py
  tests/conftest.py
  tests/test_perseptual.py
Labels: feature
