Repository photosynthesis-team/piq, pull requests merged in 2020-05, with the labels that each got.

#50 enchancement/more strict formatting verifications
  .github/workflows/ci-linting.yml
  photosynthesis_metrics/base.py
  photosynthesis_metrics/fid.py
  photosynthesis_metrics/kid.py
  photosynthesis_metrics/msid.py
  photosynthesis_metrics/ssim.py
  photosynthesis_metrics/tv.py
  photosynthesis_metrics/utils.py
  setup.py
  tests/test_fid.py
  tests/test_kid.py
  tests/test_msid.py
  tests/test_ssim.py
  tests/test_tv.py
  tox.ini
Labels: enhancement, refactoring

#53 enhancement: PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, enhancement

#62 Make workflows run from PRs
  .github/workflows/ci-linting.yml
  .github/workflows/ci-testing.yml
Labels: bug

#63 Bug/trigger ci
  .github/workflows/ci-linting.yml
  .github/workflows/ci-testing.yml
Labels: bug

#70 fix: PR template
  .github/pull_request_template.md
Labels: bug

#55 Enhancement of SSIM, MS-SSIM and TV
  photosynthesis_metrics/ssim.py
  photosynthesis_metrics/tv.py
  photosynthesis_metrics/utils.py
  tests/test_ssim.py
  tests/test_tv.py
Labels: enhancement, feature, refactoring, tests

#66 bug(tv): reduction was handled to return proper values
  photosynthesis_metrics/ssim.py
  photosynthesis_metrics/tv.py
  photosynthesis_metrics/vif.py
Labels: bug, enhancement
