Repository photosynthesis-team/piq, pull requests merged in 2020-07, with the labels that each got.

#116 Test coverate info
  .github/workflows/ci-testing.yml
  README.md
  codecov.yml
Labels: documentation, feature

#119 Add Visual Saliency-induced Index (VSI)
  README.md
  piq/__init__.py
  piq/brisque.py
  piq/functional.py
  piq/vsi.py
  tests/assets/I01.BMP
  tests/assets/i01_01_5.bmp
  tests/test_vsi.py
Labels: feature

#109 Add FSIM and FSIMc
  README.md
  piq/__init__.py
  piq/fsim.py
  piq/gmsd.py
  tests/assets/goldhill.gif
  tests/assets/goldhill_jpeg.gif
  tests/test_fsim.py
Labels: feature

#117 Address suggestions from Sonar
  README.md
  codecov.yml
  piq/brisque.py
  piq/fid.py
  piq/gs.py
  piq/msid.py
  tests/test_brisque.py
  tests/test_fid.py
  tests/test_gmsd.py
  tests/test_gs.py
  tests/test_is.py
  tests/test_kid.py
  tests/test_msid.py
Labels: refactoring

#134 Enhancement of SSIM/MS-SSIM and BRISQUE, Refactoring of tests for SSIM/MS-SSIM and BRISQUE
  piq/__init__.py
  piq/brisque.py
  piq/functional/__init__.py
  piq/functional/colour_conversion.py
  piq/functional/filters.py
  piq/ssim.py
  piq/utils/common.py
  tests/test_brisque.py
  tests/test_ssim.py
  tests/test_tv.py
  tests/test_utils.py
Labels: enhancement, refactoring, tests
