Repository photosynthesis-team/piq, pull requests merged in 2021-01, with the labels that each got.

#184 Metric: PieAPP
  README.md
  examples/image_metrics.py
  piq/__init__.py
  piq/functional/__init__.py
  piq/functional/base.py
  piq/pieapp.py
  tests/test_perseptual.py
  tests/test_pieapp.py
Labels: feature

#204 Access modifiers for feature extraction methods
  README.md
  examples/feature_metrics.py
  piq/base.py
  tests/test_fid.py
  tests/test_msid.py
Labels: refactoring

#206 README refactoring
  README.md
Labels: documentation

#217 Sphinx-based Documentation
  .readthedocs.yml
  README.md
  docs/Makefile
  docs/index.md
  docs/make.bat
  docs/requirements.txt
  docs/source/_files/benchmark.csv
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/examples.rst
  docs/source/functions.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/modules.rst
  docs/source/overview.rst
  piq/brisque.py
  piq/fid.py
  piq/fsim.py
  piq/gs.py
  piq/haarpsi.py
  piq/isc.py
  piq/mdsi.py
  piq/msid.py
  piq/perceptual.py
  piq/ssim.py
  piq/tv.py
  piq/vsi.py
Labels: documentation, enhancement

#220 Add citation of the library
  README.md
Labels: documentation
