Repository photosynthesis-team/piq, pull requests merged in 2021-09, with the labels that each got.

#268 Create intermediate tensors on correct device
  piq/dss.py
Labels: bug

#269 Benchmark metrics on PIPAL dataset
  README.rst
  tests/results_benchmark.py
Labels: enhancement

#202 Metric: SR-SIM
  README.rst
  examples/image_metrics.py
  piq/__init__.py
  piq/functional/__init__.py
  piq/functional/resize.py
  piq/srsim.py
  tests/results_benchmark.py
  tests/test_srsim.py
Labels: feature
