Repository photosynthesis-team/piq, pull requests merged in 2021-02, with the labels that each got.

#229 Documentation Guide
  CONTRIBUTING.md
  docs/source/contributing.rst
Labels: documentation, enhancement

#230 Unify input tensors name
  README.md
  docs/source/examples.rst
  examples/feature_metrics.py
  examples/image_metrics.py
  piq/base.py
  piq/brisque.py
  piq/fid.py
  piq/fsim.py
  piq/gmsd.py
  piq/gs.py
  piq/haarpsi.py
  piq/isc.py
  piq/kid.py
  piq/mdsi.py
  piq/msid.py
  piq/perceptual.py
  piq/pieapp.py
  piq/psnr.py
  piq/ssim.py
  piq/tv.py
  piq/utils/common.py
  piq/vif.py
  piq/vsi.py
  tests/conftest.py
  tests/test_fid.py
  tests/test_fsim.py
  tests/test_gmsd.py
  tests/test_gs.py
  tests/test_haarpsi.py
  tests/test_is.py
  tests/test_kid.py
  tests/test_mdsi.py
  tests/test_msid.py
  tests/test_perseptual.py
  tests/test_pieapp.py
  tests/test_psnr.py
  tests/test_ssim.py
  tests/test_tv.py
  tests/test_vif.py
  tests/test_vsi.py
Labels: enhancement, refactoring

#234 Update validation and reduction.
  README.rst
  docs/source/overview.rst
  examples/image_metrics.py
  piq/base.py
  piq/brisque.py
  piq/fid.py
  piq/fsim.py
  piq/gmsd.py
  piq/gs.py
  piq/haarpsi.py
  piq/isc.py
  piq/kid.py
  piq/mdsi.py
  piq/msid.py
  piq/perceptual.py
  piq/pieapp.py
  piq/psnr.py
  piq/ssim.py
  piq/tv.py
  piq/utils/__init__.py
  piq/utils/common.py
  piq/vif.py
  piq/vsi.py
  tests/conftest.py
  tests/test_brisque.py
  tests/test_fsim.py
  tests/test_gmsd.py
  tests/test_haarpsi.py
  tests/test_perseptual.py
  tests/test_pieapp.py
  tests/test_psnr.py
  tests/test_ssim.py
  tests/test_tv.py
  tests/test_utils.py
  tests/test_vif.py
  tests/test_vsi.py
Labels: refactoring
